services:
  - type: web
    name: project-generation
    env: docker
    dockerfilePath: ./Dockerfile
    # buildCommand: docker build -t project-generation .
    # startCommand: docker run -p 8000:8000 project-generation
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: ALLOWED_HOSTS
        value: .onrender.com